version: "3"
services:

  DBpostgres:
    image: postgres:11
    container_name: Iceberg
    restart: always
    environment:
      - POSTGRES_DB=Iceberg
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
  # docker-python:
  #       build:
  #           context: .
  #       ports:
  #       - 8000:5000
  #       depends_on:
  #       - DBpostgres
